name: Ceedling Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby and Ceedling
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev rake
          sudo gem install ceedling

      - name: Run Ceedling tests
        working-directory: ./core
        run: ceedling test:all
